<?php
  $scheduleSupported = !empty($this->schedule);
  $saveSupported = $this->accountCapabilities()->getSavedSearchSetting() === 'enabled';
?>




<div class="save_search_table_wraper">
<table class="search-history-table" id="<?=$this->showSaved ? 'saved-searches' : 'recent-searches'?>">
  <tr>
    <th width="20%"><?=$this->transEsc("history_time")?></th>
    <th><?=$this->transEsc("history_search")?></th>
    <th><?=$this->transEsc("history_limits")?></th>
    <th><?=$this->transEsc("history_results")?></th>
    <?php if ($scheduleSupported): ?><th class="search-schedule-header"><?=$this->transEsc('history_schedule')?></th><?php endif; ?>
    <?php if ($saveSupported): ?><th><?=$this->transEsc($this->showSaved ? "history_delete" : "history_save")?></th><?php endif; ?>
  </tr>
  <?php foreach (($this->showSaved ? array_reverse($this->saved) : array_reverse($this->unsaved)) as $iteration => $info): ?>
    <tr class="<?=$iteration % 2 == 1 ? 'even' : 'odd'?>row">
      <td><?=$this->escapeHtml($this->dateTime()->convertToDisplayDateAndTime("U", $info->getStartTime()))?></td>
      <td>
        <?=$this->historylabel($info->getParams()->getSearchClassId())?>
        <a href="<?=$this->url($info->getOptions()->getSearchAction()) . $info->getUrlQuery()->getParams()?>"><?php
          $desc = $info->getParams()->getDisplayQuery();
          echo empty($desc) ? $this->transEsc("history_empty_search") : $this->escapeHtml($desc);
        ?></a>
      </td>
      <td>
        <?php foreach ($info->getParams()->getFilterList(true) as $field => $filters): ?>
          <?php foreach ($filters as $i => $filter): ?>
            <?php if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?>
            <strong><?=$this->transEsc($field)?></strong>: <?=$this->escapeHtml($filter['displayText'])?><br/>
          <?php endforeach; ?>
        <?php endforeach; ?>
        <?php foreach($info->getParams()->getCheckboxFacets() as $facet): ?>
          <?php if ($facet['selected']): ?>
            <strong><?=$this->transEsc($facet['desc'])?></strong><br/>
          <?php endif; ?>
        <?php endforeach; ?>
      </td>
      <td><?=$this->escapeHtml($this->localizedNumber($info->getResultTotal()))?></td>
      <?php if ($scheduleSupported): ?>
        <td>
        <?php if (isset($this->schedule[$info->getSearchId()])): ?>
          <?php $schedule = $this->schedule[$info->getSearchId()]; ?>
            <form class="form-inline jumpMenuForm" action="<?= $this->url('myresearch-savesearch')?>" method="get" name="schedule">
              <select name="schedule" class="jumpMenu form-control" aria-haspopup="true" title="<?=$this->transEscAttr("history_schedule")?>">
                <?php foreach ($scheduleOptions as $scheduleValue => $scheduleLabel): ?>
                  <option value="<?=$this->escapeHtmlAttr($scheduleValue)?>"<?=($schedule == $scheduleValue) ? (' selected') : ('')?>><?=$this->transEsc($scheduleLabel)?></option>
                <?php endforeach; ?>
              </select>
              <input type="hidden" name="searchid" value="<?=$this->escapeHtmlAttr($info->getSearchId()) ?>"/>
            </form>
          <?php else: ?>
            <span class="disable"><?=$this->transEsc("cannot set")?></span>
          <?php endif; ?>
        </td>
      <?php endif; ?>
      <?php if ($saveSupported): ?>
        <td>
          <?php if ($this->showSaved): ?>
            <a href="<?=$this->url('myresearch-savesearch')?>?delete=<?=urlencode($info->getSearchId())?>&amp;mode=history" class="text-danger">
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M5 2V0H15V2H20V4H18V19C18 19.2652 17.8946 19.5196 17.7071 19.7071C17.5196 19.8946 17.2652 20 17 20H3C2.73478 20 2.48043 19.8946 2.29289 19.7071C2.10536 19.5196 2 19.2652 2 19V4H0V2H5ZM4 4V18H16V4H4ZM7 7H9V15H7V7ZM11 7H13V15H11V7Z" fill="#FF1D53"/>
            </svg>
           </a>
          <?php else: ?>
            <a href="<?=$this->url('myresearch-savesearch')?>?save=<?=urlencode($info->getSearchId())?>&amp;mode=history"><i class="fa fa-save" aria-hidden="true"></i> <?=$this->transEsc("history_save_link")?></a>
          <?php endif; ?>
        </td>
      <?php endif; ?>
    </tr>
  <?php endforeach; ?>
</table>
</div>



