<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  $this->layout()->breadcrumbs = false;
?>
<div class="welcome_banner_area_wrap"><!--Welcome Banner Area Start-->

<img class="bannerbg" src="/vufind/themes/equinox/images/small/banner-imgs.jpg" alt="">
</div>
<div class="search search_wrapper">
  <div class="searchbox hidden-print" role="search">
    <div class="container">
  <?php $this->slot('search-home-hero')->start() ?>
    <?=$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
  <?=$this->slot('search-home-hero')->end() ?>
</div>
  </div>
</div>

<?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>

<div class="home_page_content">


<div class="home_page_content mainbody">

</div>

</div>
