<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  $this->layout()->breadcrumbs = false;
?>
<div class="welcome_banner_area_wrap"><!--Welcome Banner Area Start-->

<div class="welcome_banner_content_wraper">
		
<div class="welcome_banner-right">
  <img src="/vufind/themes/equinox/images/small/home-banner-logo.png" alt="banner Image">
</div>
</div>

<img class="bannerbg" src="/vufind/themes/equinox/images/small/banner-imgs.jpg" alt="bannerbg">
</div>
<div class="searchHomeContent">
<h2>Browse through all of the library’s resources</h2>
  <?php $this->slot('search-home-hero')->start() ?>
    <?=$this->context($this)->renderInContext("search/searchbox.phtml", ['ignoreHiddenFilterMemory' => true])?>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$("#searchForm_lookfor").focus();', 'SET'); ?>
  <?=$this->slot('search-home-hero')->end() ?>
</div>



<?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>












<div class="home_page_content">
<div class="menu_opening_overlay" style="height: 100%!important;margin-top: 0!important"></div>




<div class="logout_body_wraper">




<div class="home_page_content mainbody">
     <div class="slider_area_in_home_page">
     <div class="owl-carousel owl-theme">

	</div>
     </div>

</div>


</div>








</div>
