


<?php $this->headTitle($this->translate('Help')); 


$this->layout()->breadcrumbs .= '<li class="active">' . $this->escapeHtml($headTitle) . '</li>';

?>
 <?php // Set up the search box -- there are three possible cases:
      // 1. No search box was set; we should default to the normal box
      // 2. It was set to false; we should display nothing
      // 3. It is set to a custom string; we should display the provided version
      // Set up default search box if no data was provided from the template;
      // this covers case 1.  Cases 2 and 3 are then covered by logic below.
      if (!isset($this->layout()->searchbox)) {
        $this->layout()->searchbox = $this->render('search/searchbox.phtml');
      }
    ?>
<header class="hidden-print">
      <?php if (isset($this->layout()->srmessage)): // message for benefit of screen-reader users ?>
        <span class="sr-only" role="heading" aria-level="1"><?=$this->layout()->srmessage ?></span>
      <?php endif; ?>
      <a class="sr-only" href="#content"><?=$this->transEsc('Skip to content') ?></a>
      <?=$this->render('header.phtml')?>
    </header>
























    
    <nav class="breadcrumbs" aria-label="<?=$this->transEscAttr('Breadcrumbs') ?>">
      <div class="container">
        <?php if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
          && !empty($this->layout()->breadcrumbs)
          && $this->layout()->breadcrumbs !== false
        ): ?>
          <ul class="breadcrumb hidden-print"><?=$this->layout()->breadcrumbs ?></ul>
        <?php endif; ?>
      </div>
    </nav>


      <div class="main">
      <div class="menu_opening_overlay" style=""></div>
        <div class="search_page_design_help_tips">

            <?php if ($help = $this->helpText()->render($topic)): ?>
              <?php foreach ($this->helpText()->getWarnings() as $warning): ?>
                <p class="alert alert-warning"><?=$this->transEsc($warning)?></p>
              <?php endforeach; ?>
              <?=$help?>
            <?php else: ?>
              <p class="alert alert-danger"><?=$this->transEsc('help_page_missing')?></p>
            <?php endif; ?> 
            </div>
      </div>

<?=$this->render('footer.phtml')?>
