<?php
    // Set up page title:
    $this->headTitle($this->translate('My Fines'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Fines') . '</li>';
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>





<div class="fince_page_wraper_body_content">



<div class="side_bar_left <?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'fines'])?>
</div>



<div  class=" update_fince_page_right_content <?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Fines')?></h2>
  <?=$this->flashmessages()?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <?php if (empty($this->fines)): ?>
    <?=$this->transEsc('You do not have any fines')?>
  <?php else: ?>
    <?php
      // Collect the data to build the table; we process this in advance so we
      // can omit empty columns and simplify customization by separating data
      // processing from rendering.
      $tableData = [];
      $totalDue = 0;
      foreach ($this->fines as $record) {
          if (empty($record['title'])) {
              $title = $this->transEsc('not_applicable');
          } elseif (!is_object($record['driver'] ?? null)) {
              $title = $this->escapeHtml(trim($record['title'], '/:'));
          } else {
              $title = '<a href="'
                  . $this->escapeHtmlAttr($this->recordLinker()->getUrl($record['driver']))
                  . '">' . $this->escapeHtml(trim($record['title'], '/:')) . '</a>';
          }
          $tableData['Title'][] = $title;
          $tableData['Checked Out'][] = $this->escapeHtml($record['checkout'] ?? '');
          $tableData['Due Date'][] = $this->escapeHtml($record['duedate'] ?? '');
          $tableData['Fine'][] = $this->transEsc($record['fine'] ?? '');
          $tableData['Fine Date'][] = $this->escapeHtml($record['createdate'] ?? '');
          $tableData['Fee'][] = isset($record['amount'])
              ? $this->safeMoneyFormat($record['amount'] / 100.00) : '';
          $tableData['Balance'][] = isset($record['balance'])
              ? $this->safeMoneyFormat($record['balance'] / 100.00) : '';
          $totalDue += $record['balance'] ?? 0;
      }

      // Now empty out any unused columns:
      foreach ($tableData as $column => $values) {
          $empty = true;
          foreach ($values as $value) {
              if (strlen($value) > 0) {
                  $empty = false;
                  break;
              }
          }
          if ($empty) {
              unset($tableData[$column]);
          }
      }

      // Create the final list of columns and count of rows:
      $columns = array_keys($tableData);
      $rowCount = count($this->fines);
    ?>
    <div class="fines_table">


    <table class="table table-striped remove_for_mobile">
      <caption class="sr-only"><?=$this->transEsc('Your Fines')?></caption>
      <tr>
        <?php foreach ($columns as $header): ?>
          <th><?=$this->transEsc($header)?></th>
        <?php endforeach; ?>
      </tr>
      <?php for ($row = 0; $row < $rowCount; $row++): ?>
        <tr>
          <?php foreach ($columns as $column): ?>
            <td><?=$tableData[$column][$row]?></td>
          <?php endforeach; ?>
        </tr>
      <?php endfor; ?>
      <tr style="font-weight:bold">
        <td colspan="<?=count($columns) - 1?>"><?=$this->transEsc('Total Balance Due')?></td>
        <td><?=$this->safeMoneyFormat($totalDue / 100.00) ?></td>
      </tr>
    </table>


  <div class="new_fines_table_for_mobile" style="display: none">
      <div class="mheader_area">
        <div class="left_side_area">
          <a href="#">Previous</a>
        </div>
        <div class="right_side_area">
          <a href="#">Next</a>
        </div>
      </div>
    <div class="main_content_area">
          <div class="header_area">
              <?php foreach ($columns as $header): ?>
                <h4><?=$this->transEsc($header)?></h4>
              <?php endforeach; ?>
          </div>
          <div class="content_area">
          <?php for ($row = 0; $row < $rowCount; $row++): ?> 
              <?php foreach ($columns as $column): ?>
                  <p><?=$tableData[$column][$row]?></p>
                <?php endforeach; ?>
              <?php endfor; ?>
        </div>
    </div>

    <div class="footer_area">
      <div class="left_side_area">
        <h4 colspan="<?=count($columns) - 1?>"><?=$this->transEsc('Total Balance Due')?></h4>
      </div>
      <div class="right_side_area">
        <p><?=$this->safeMoneyFormat($totalDue / 100.00) ?></p>
      </div>
    </div>




  </div>

    </div>
  <?php endif; ?>
</div>

</div>









<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'fines', 'accountStatus' => $this->accountStatus]); ?>
