<footer class="hidden-print">
  <div class="footer-container">
    <div class="footer-column">
          <h2>Library Name</h2>
          <ul>
            <li>55 Main Street</li>
            <li>Atlanta, GA 30368</li>
            <li>Tel. 555-555-5555</li>
            <li>Fax 555-555-5555</li>
          </ul>
    </div>

    <div class="footer-column">
      <h2>Library Hours</h2>
      <ul>
        <li>Mon to Thurs: 9am – 8pm</li>
        <li>Friday: 9am – 6pm</li>
        <li>Saturday: 9am – 5pm</li>
        <li>Sunday: 1pm – 4pm</li>
      </ul>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-left')->start(); ?>
        <h2><?=$this->transEsc('Search Options')?></h4>
        <ul>
          <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
          <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
        </ul>
      <?=$this->slot('footer-left')->end(); ?>
    </div>
    <div class="footer-column">
      <?php $this->slot('footer-right')->start(); ?>
        <h2><?=$this->transEsc('Need Help?')?></h2>
        <ul>
          <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'asklibrary']) ?>"><?=$this->transEsc('Ask a Librarian')?></a></li>
          <li><a href="<?=$this->url('content-page', ['page' => 'faq']) ?>"><?=$this->transEsc('FAQs')?></a></li>
        </ul>
      <?=$this->slot('footer-right')->end(); ?>
    </div>
  </div>

  <div class="subfooter">
    <div class="container">
      <div class="footer_copyright">
        <p>Copyright &copy; 2022 [Library Name]. All rights reserved.</p>
      </div>
      <ul class="footer-social">
        <li><a href="#"><i class="fa fa-twitter"></i><span class="sr-only">Twitter</span></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i><span class="sr-only">Instagram</span></a></li>
        <li><a href="#"><i class="fa fa-facebook"></i><span class="sr-only">Facebook</span></a></li>
      </ul>
    </div>
  

    <div class="poweredby">
      <?=$this->layout()->poweredBy ?>
    </div>

    </div>
</footer>
