<?php $account = $this->auth()->getManager(); ?>
<div class="top_header_content">
<div class="banner container navbar">
  <div class="navbar-header">
  <h1 class="site_logo"><a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home')?>"><img src="/vufind/themes/equinox/images/small/vufind-logo-white.svg" alt="VuFind"></a></h1>
  
  <div class="mobile_navbar_new" style="display: inline-block">
   <a href="<?php if(!$account->isLoggedIn()): ?>  <?=$this->url('myresearch-userlogin')?> <?php else: ?> <?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?><?php endif ?>" class="mobile_login_button"><?php if(!$account->isLoggedIn()): ?> Login<?php else: ?> Account<?php endif ?></a>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse" aria-hidden="true">
      <i class="fa fa-bars"><span class="sr-only">Menu</span></i>
    </button>
   </div>
  </div>
  <?php if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <nav>
        <ul class="nav navbar-nav navbar-right flip">
          <?php if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
            </li>
          <?php endif; ?>
          <?php $cart = $this->cart(); if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" data-lightbox title="<?=$this->transEscAttr('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
                <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
              </a>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="theme dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->themeOptions as $current): ?>
                  <li<?=$current['selected'] ? ' class="active"' : ''?>>
                    <a href="<?=$this->escapeHtmlAttr($this->url()->addQueryParameters(['ui' => $current['name']])) ?>" rel="nofollow">
                      <?=$this->transEsc($current['desc']) ?>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>

          <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="language dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>>
                    <a href="<?=$this->escapeHtmlAttr($this->url()->addQueryParameters(['lng' => $langCode])) ?>" rel="nofollow">
                      <?=$this->displayLanguageOption($langName) ?>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>

          <li><a href="#">Programs &amp; Services</a></li>
          <li><a href="#">Get a Library Card</a></li>
          <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
         <li class="logoutOptions<?php if($account->dropdownEnabled()): ?> with-dropdown<?php endif ?><?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>"><i id="account-icon" class="fa fa-user-circle" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
            </li>
            <?php if($account->dropdownEnabled()): ?>
              <li id="login-dropdown" class="dropdown<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
                <a href="#" data-toggle="dropdown"><i class="fa fa-caret-down"></i></a>
                <div class="dropdown-menu">
                  <?=$this->render('myresearch/menu'); ?>
                </div>
              </li> 
            <?php endif; ?>


          <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
            </li>



            <!-- <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
              <a href="<?=$this->url('content-page', ['page' => 'helptips']) ?>"><?=$this->transEsc('Help Tips')?></a>
            </li> -->


            <li id="loginOptions"<?php if($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
              <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
              <?php else: ?>
                <a href="<?=$this->url('myresearch-userlogin')?>" ><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
              <?php endif; ?>
            </li>
          <?php endif; ?>


        </ul>
      </nav>
    </div>
  <?php endif; ?>
</div>

</div>

<?php if ($this->layout()->searchbox !== false): ?>
  <div class="welcome_banner_area_wrap"><!--Welcome Banner Area Start-->

<img class="bannerbg" src="/vufind/themes/equinox/images/small/banner-img-cropped.jpg" alt="bannerbg">
</div>

  <div class="search search_wrapper">
    <div class="container searchbox hidden-print" role="search">
      <?=$this->layout()->searchbox ?>
    </div>
  </div>
<?php endif; ?>
